# Site settings
title: Karthik Sankar
description: Mobile Developer â¤ï¸ to code in Swift. You can find me with my Mac and AirPods all day long. AR and ML are my new addictsğŸ‰.

# User settings
username: Karthik Sankar
user_description: Mobile Developer â¤ï¸ to code in Swift. You can find me with my Mac and AirPods all day long. AR and ML are my new addictsğŸ‰.
user_title: Mobile Developer
email: karthiks94one@gmail.com
twitter_username: karthiks94one
github_username:  KarthikS941

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
